services:
  postgres_a:
    image: postgres:latest
    container_name: postgres_a
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: banco_a
    volumes:
      - pgdata_a:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  postgres_b:
    image: postgres:latest
    container_name: postgres_b
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: banco_b
    volumes:
      - pgdata_b:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata_a:
  pgdata_b:

